### ISSUE TITLE
Build and Dev fails after unhead module is added

### ISSUE THREAD

**Issue by just-maik** [harlan-zw/nuxt-unhead#6]
### Describe the bug

When using the unhead module with nuxt@3.2.2 it doesnt build anymore and errors

```
 ERROR  Cannot start nuxt:  root is not defined                                                                                   12:53:09

  at config (node_modules/@unhead/addons/dist/shared/addons.ba318fee.mjs:57:9)
  at runConfigHook (node_modules/vite/dist/node/chunks/dep-ca21228b.js:62375:31)                                                  12:53:03
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async resolveConfig (node_modules/vite/dist/node/chunks/dep-ca21228b.js:61876:14)
  at async Module.createServer (node_modules/vite/dist/node/chunks/dep-ca21228b.js:61153:20)
  at async buildClient (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.a46e9c8e.mjs:434:24)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.a46e9c8e.mjs:1048:3)
  at async build (node_modules/nuxt/dist/index.mjs:2675:5)
  at async Promise.all (index 1)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6809:9)
```

I've tested this on npm, yarn and pnpm (using shamefully hoist).

### Reproduction

https://stackblitz.com/edit/nuxt-starter-c3moa1?file=nuxt.config.ts

### System Info

```Shell
System:
    OS: Linux 5.4 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: //
    Memory: 22.16 GB / 31.36 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.18.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by just-maik** [comment]
When running DEBUG=* nuxi dev it logs the following before crashing
```
[nuxt] vite:extendConfig: 0.055ms                                                                         14:16:57
vite:config no config file found. +32s   
```

I get this error even though I now explicitly tell vite to use "/app" as root
```ts
export default defineNuxtConfig({
  modules: ['nuxt-unhead'],
  vite: {
    root: '/app',
  },
});
```

**Comment by gyxoBka** [comment]
same problem but i have layouts

**Comment by harlan-zw** [comment]
Hey @just-maik, thanks for the issue!

This was a bug introduced in v1.1.0 of @unhead/addons. 

I've pushed up a fix in this repo and nuxt-seo-kit, please update to the latest :)
