### ISSUE TITLE
Cannot read properties of undefined (reading 'use')

### ISSUE THREAD

**Issue by rzouhair** [harlan-zw/nuxt-unhead#8]
### Details

Hi, this issue happened to me after installing nuxt-seo-kit, at first nothing worked until I upgraded my local node version, but now, each time my nuxt.config.ts updates, or I restart my dev server, this issue occurs, and I need to delete node_modules .nuxt and reinstall all packages.

I don't know if anyone have encountered this issue before, Thanks

some additional info:
pnpm version: 7.28.0
node version: lts/gallium
nuxt version: 3.2.2
nuxt-seo-kit version: 1.3.1

----

Console warning:

chunk-Q53DPCWL.js?v=08e16e01:1381 [Vue warn]: Hydration node mismatch:
- Client vnode: div 
- Server rendered DOM:  (start of fragment) 
  at <ErrorDev statusCode=500 statusMessage="Internal Server Error" description="Cannot read properties of undefined (reading 'use')"  ... > 
  at <AsyncComponentWrapper statusCode=500 statusMessage="Internal Server Error" description="Cannot read properties of undefined (reading 'use')"  ... > 
  at <NuxtErrorPage key=0 error= TypeError: Cannot read properties of undefined (reading 'use')
    at plugin.mjs?v=08e16e01:9:10
    at fn (nuxt.mjs?v=08e16e01:146:27)
    at callWithNuxt (nuxt.mjs?v=08e16e01:151:12)
    at applyPlugin (nuxt.mjs?v=08e16e01:97:29)
    at applyPlugins (nuxt.mjs?v=08e16e01:106:11)
    at async initApp (entry.mjs:39:7) > 
  at <AsyncComponentWrapper key=0 error= TypeError: Cannot read properties of undefined (reading 'use')
    at plugin.mjs?v=08e16e01:9:10
    at fn (nuxt.mjs?v=08e16e01:146:27)
    at callWithNuxt (nuxt.mjs?v=08e16e01:151:12)
    at applyPlugin (nuxt.mjs?v=08e16e01:97:29)
    at applyPlugins (nuxt.mjs?v=08e16e01:106:11)
    at async initApp (entry.mjs:39:7) > 
  at <NuxtRoot>

-----

Error page message:

500

Cannot read properties of undefined (reading 'use')

at http://localhost:3000/_nuxt/node_modules/.pnpm/nuxt-unhead@1.4.6/node_modules/nuxt-unhead/dist/runtime/plugin.mjs?v=08e16e01:9:10
at fn (http://localhost:3000/_nuxt/node_modules/.pnpm/nuxt@3.2.2/node_modules/nuxt/dist/app/nuxt.mjs?v=08e16e01:146:27)
at callWithNuxt (http://localhost:3000/_nuxt/node_modules/.pnpm/nuxt@3.2.2/node_modules/nuxt/dist/app/nuxt.mjs?v=08e16e01:151:12)
at applyPlugin (http://localhost:3000/_nuxt/node_modules/.pnpm/nuxt@3.2.2/node_modules/nuxt/dist/app/nuxt.mjs?v=08e16e01:97:29)
at applyPlugins (http://localhost:3000/_nuxt/node_modules/.pnpm/nuxt@3.2.2/node_modules/nuxt/dist/app/nuxt.mjs?v=08e16e01:106:11)
at async initApp (http://localhost:3000/_nuxt/Users/ayoubel/Projects/blog/node_modules/.pnpm/nuxt@3.2.2/node_modules/nuxt/dist/app/entry.mjs:39:7)

Thanks

**Comment by harlan-zw** [comment]
Hey @rzouhair, thanks for the issue

Please try the latest version, if you still have issues you may need to wait until the next Nuxt patch which will be in the next couple of days.

**Comment by rzouhair** [comment]
Thanks @harlan-zw for the reply, appreciate it.

Can I use nuxt/unhead along with nuxt-seo-kit ? as far as I know, nuxt unhead is intergrated in nuxt-seo-kit, so I don't know if they are compatible,

Thanks

**Comment by harlan-zw** [comment]
Yes! It's one of the reasons I made Nuxt SEO Kit to increase the number of people using this package, allowing me to test out features quicker before I push them into the Nuxt core.

**Comment by rzouhair** [comment]
Thank you very much, appreciate your help

**Comment by harlan-zw** [comment]
Interesting, thanks! Think this is a nuxt layer issue
